# -*- coding: utf-8 -*-
"""빅데이터프로젝트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15JZkCP3a-Afn-b_P5HYnD9Sznvyc9lT6
"""

# 폰트 설치
import matplotlib.font_manager as fm
!apt-get -qq -y install fonts-nanum > /dev/null
fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf' 
font = fm.FontProperties(fname=fontpath, size=9)
fm._rebuild()

# 런타임 재시작 
import os 
os.kill(os.getpid(), 9)

# 한글 폰트 설정
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm

# 마이너스 표시 문제
mpl.rcParams['axes.unicode_minus'] = False
	
# 한글 폰트 설정
path = '/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf'
font_name = fm.FontProperties(fname=path, size=18).get_name()
plt.rc('font', family=font_name)
fm._rebuild()

import pandas as pd 
import seaborn as sns

# 데이터 프레임 생성
df = pd.read_csv('/content/crime.csv',encoding='cp949')
df

# 요일 항목만 남기고 제거한 wdf 구하기
wdf = df.drop(['범죄중분류',
               '0시00분-02시59분','03시00분-05시59분','06시00분-08시59분',
               '09시00분-11시59분','12시00분-14시59분','15시00분-17시59분',
               '18시00분-20시59분','21시00분-23시59분','미상'], axis=1)

# 범죄대분류 별로 합계를 구해 요일별로 저장
wdf = wdf.groupby('범죄대분류').sum()

# 행, 열 전환
wdf = wdf.transpose()

wdf

wdf.plot(kind='bar', stacked='True')
plt.title('요일별 범죄 발생 건수')
plt.xlabel('요일')
plt.ylabel('범죄 발생 건수')

# 범주 박스 위치 지정
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
plt.show()